# Generated by Django 5.0.1 on 2024-04-29 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Financial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("date_doc", models.DateTimeField(blank=True, null=True)),
                ("CostType", models.CharField(blank=True, max_length=255, null=True)),
                ("descr", models.TextField(blank=True, null=True)),
                ("F_conf", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("programId", models.CharField(blank=True, max_length=255, null=True)),
                ("topicId", models.CharField(blank=True, max_length=255, null=True)),
                ("rowId", models.CharField(blank=True, max_length=255, null=True)),
                ("tax", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LogisticsUploads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="./uploads/")),
                ("name", models.CharField(max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="LogisticsUploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Logistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("type", models.BooleanField(default=True)),
                ("price", models.FloatField(blank=True, null=True)),
                ("seller", models.CharField(blank=True, max_length=255)),
                ("seller_id", models.CharField(blank=True, max_length=255)),
                ("date_doc", models.DateTimeField(blank=True)),
                ("Location", models.CharField(blank=True, max_length=255)),
                ("Payment_type", models.BooleanField(blank=True, default=True)),
                ("descr", models.TextField(blank=True)),
                ("F_conf", models.BooleanField(blank=True, default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("measure", models.CharField(blank=True, max_length=255, null=True)),
                ("CostDriver", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "Fdoc_key",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Logistics",
                        to="tadbirbodjeh.financial",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Logistics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploads",
                    models.ManyToManyField(
                        blank=True, to="tadbirbodjeh.logisticsuploads"
                    ),
                ),
            ],
        ),
    ]
