# Generated by Django 5.0.1 on 2024-07-01 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="budget_chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(blank=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("year", models.CharField(blank=True, max_length=255, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="credit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("year", models.CharField(blank=True, max_length=255, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("descr", models.TextField(blank=True)),
                ("price_public", models.FloatField(blank=True, null=True)),
                ("price_pubic", models.FloatField(blank=True, null=True)),
                ("price_pubic_transfer", models.FloatField(blank=True, null=True)),
                ("price_exclusive", models.FloatField(blank=True, null=True)),
                ("price_exclusiveـtransfer", models.FloatField(blank=True, null=True)),
                ("price_other", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="sub_unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="budget_section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(blank=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "budget_chapter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_section",
                        to="tadbirbodjeh.budget_chapter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="budget_row",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(blank=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "budget_section",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_row",
                        to="tadbirbodjeh.budget_section",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Financial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="بدون نام", max_length=255),
                ),
                ("date_doc", models.DateTimeField(blank=True, null=True)),
                ("CostType", models.CharField(blank=True, max_length=255, null=True)),
                ("descr", models.TextField(blank=True, null=True)),
                (
                    "fin_state",
                    models.IntegerField(
                        choices=[(0, "start"), (1, "cheek"), (2, "final")], default=0
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("programId", models.CharField(blank=True, max_length=255, null=True)),
                ("topicId", models.CharField(blank=True, max_length=255, null=True)),
                ("rowId", models.CharField(blank=True, max_length=255, null=True)),
                ("tax", models.CharField(blank=True, max_length=255, null=True)),
                ("Payment_type", models.BooleanField(blank=True, default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LogisticsUploads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="./uploads/")),
                ("name", models.CharField(max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="LogisticsUploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PettyCash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("doc_num", models.CharField(blank=True, max_length=255)),
                ("date_doc", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("price", models.FloatField(blank=True, null=True)),
                ("F_conf", models.BooleanField(blank=True, default=False)),
                ("descr", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pettycash",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Logistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("type", models.BooleanField(default=True)),
                ("price", models.FloatField(blank=True, null=True)),
                ("seller", models.CharField(blank=True, max_length=255)),
                ("seller_id", models.CharField(blank=True, max_length=255)),
                ("date_doc", models.DateTimeField(blank=True)),
                ("descr", models.TextField(blank=True)),
                ("F_conf", models.BooleanField(blank=True, default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("measure", models.CharField(blank=True, max_length=255, null=True)),
                ("CostDriver", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "Fdoc_key",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logistics",
                        to="tadbirbodjeh.financial",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Logistics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploads",
                    models.ManyToManyField(
                        blank=True, to="tadbirbodjeh.logisticsuploads"
                    ),
                ),
                (
                    "Location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Logistics",
                        to="tadbirbodjeh.sub_unit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unit",
                        to="tadbirbodjeh.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sub_unit",
            name="unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_unit",
                to="tadbirbodjeh.unit",
            ),
        ),
    ]
