# Generated by Django 5.0.1 on 2024-04-29 11:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tadbirbodjeh", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financial",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="logistics",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="logisticsuploads",
            name="created_by",
        ),
    ]
