# Generated by Django 5.0.1 on 2024-09-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tadbirbodjeh", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sub_unit",
            name="code",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="sub_unit",
            name="year",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
