# Generated by Django 5.0.1 on 2024-09-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tadbirbodjeh", "0002_sub_unit_code_sub_unit_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("year", models.CharField(blank=True, max_length=255, null=True)),
                ("code", models.IntegerField(blank=True, default=0, null=True)),
                ("fin_code", models.IntegerField(blank=True, default=0, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("general_cost", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "specific_cost",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("other_cost", models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
