# Generated by Django 5.0.1 on 2024-07-14 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tadbirbodjeh",
            "0002_logistics_account_name_logistics_account_number_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pettycash",
            name="L_conf",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="pettycash",
            name="forwhom",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pettycashowner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
