# Generated by Django 5.0 on 2024-02-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tadbirbodjeh", "0002_financial_logistics_logisticsuploads_delete_todo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financial",
            name="programId",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="financial",
            name="rowId",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="financial",
            name="topicId",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="logistics",
            name="CostDriver",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="logistics",
            name="measure",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
