# Generated by Django 5.0.1 on 2024-10-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tadbirbodjeh", "0002_contractor_type_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="performanceـwithholding",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="performanceـwithholding_percentage",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="Contractor",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="contract",
            name="Contractor_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="contract",
            name="account_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="account_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="bank_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="contract_number",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="contract",
            name="cost_type",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="descr",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="document_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="contract",
            name="final_payable_amount",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="contract",
            name="overhead_percentage",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="paid_amount",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="payable_amount_after_deductions",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="requested_performance_amount",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="tax_amount",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="tax_percentage",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="total_contract_amount",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="treasury_deduction_percent",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="uploads",
            field=models.ManyToManyField(null=True, to="tadbirbodjeh.logisticsuploads"),
        ),
    ]
