# Generated by Django 5.0.1 on 2024-10-01 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tadbirbodjeh", "0003_program"),
    ]

    operations = [
        migrations.CreateModel(
            name="relation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(blank=True, max_length=255, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("budget_sub_row", models.BooleanField(default=False)),
                ("cost_type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "budget_row",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relations",
                        to="tadbirbodjeh.budget_row",
                    ),
                ),
                (
                    "programs",
                    models.ManyToManyField(
                        related_name="relations", to="tadbirbodjeh.program"
                    ),
                ),
                (
                    "sub_unit",
                    models.ManyToManyField(
                        related_name="relations", to="tadbirbodjeh.sub_unit"
                    ),
                ),
            ],
        ),
    ]
