# Generated by Django 5.0.1 on 2024-07-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tadbirbodjeh", "0003_pettycash_l_conf_pettycash_forwhom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pettycash",
            name="F_conf",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pettycash",
            name="L_conf",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
