# Generated by Django 5.0 on 2024-03-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tadbirbodjeh",
            "0003_alter_financial_programid_alter_financial_rowid_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="logistics",
            name="seller_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="logistics",
            name="CostDriver",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="logistics",
            name="F_conf",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="logistics",
            name="Location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="logistics",
            name="Payment_type",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="logistics",
            name="date_doc",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="logistics",
            name="descr",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="logistics",
            name="measure",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="logistics",
            name="price",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="logistics",
            name="seller",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
