# Generated by Django 5.0.1 on 2024-11-03 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tadbirbodjeh", "0003_contract_performanceـwithholding_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="final_payable_amount",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="overhead_percentage",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="paid_amount",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="payable_amount_after_deductions",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="performanceـwithholding",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="performanceـwithholding_percentage",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="requested_performance_amount",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="tax_amount",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="tax_percentage",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="treasury_deduction_percent",
        ),
        migrations.AlterField(
            model_name="contract",
            name="Contractor_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="tadbirbodjeh.contractor_type",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="Location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="tadbirbodjeh.sub_unit",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="budget_row",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="tadbirbodjeh.budget_row",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="program",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="tadbirbodjeh.program",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="uploads",
            field=models.ManyToManyField(to="tadbirbodjeh.logisticsuploads"),
        ),
        migrations.CreateModel(
            name="Contract_record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paid_amount", models.FloatField(null=True)),
                (
                    "requested_performance_amount",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "treasury_deduction_percent",
                    models.CharField(max_length=255, null=True),
                ),
                ("overhead_percentage", models.CharField(max_length=255, null=True)),
                (
                    "performanceـwithholding",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "performanceـwithholding_percentage",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "payable_amount_after_deductions",
                    models.CharField(max_length=255, null=True),
                ),
                ("tax_percentage", models.CharField(max_length=255, null=True)),
                ("tax_amount", models.CharField(max_length=255, null=True)),
                ("final_payable_amount", models.CharField(max_length=255, null=True)),
                ("insurance", models.CharField(max_length=255, null=True)),
                (
                    "advance_payment_deductions",
                    models.CharField(max_length=255, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("descr", models.TextField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Contractor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contract",
            name="Contract_record",
            field=models.ManyToManyField(
                related_name="contracts", to="tadbirbodjeh.contract_record"
            ),
        ),
    ]
