# Generated by Django 5.0.1 on 2024-09-08 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tadbirbodjeh", "0004_alter_pettycash_f_conf_alter_pettycash_l_conf"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budget_chapter",
            name="updated",
        ),
        migrations.AddField(
            model_name="budget_row",
            name="year",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="budget_section",
            name="year",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="logisticsuploads",
            name="created_by",
            field=models.ForeignKey(
                max_length=500,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="LogisticsUploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
