# Generated by Django 5.0.1 on 2024-10-01 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tadbirbodjeh", "0004_relation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relation",
            name="cost_type",
        ),
        migrations.RemoveField(
            model_name="relation",
            name="programs",
        ),
    ]
