# Generated by Django 5.0 on 2024-03-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tadbirbodjeh",
            "0004_logistics_seller_id_alter_logistics_costdriver_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logisticsuploads",
            name="Logistics",
        ),
        migrations.AddField(
            model_name="logistics",
            name="upload_ids",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="logisticsuploads",
            name="file",
            field=models.FileField(upload_to="./uploads/"),
        ),
    ]
