# Generated by Django 5.0.1 on 2024-09-08 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tadbirbodjeh", "0005_remove_budget_chapter_updated_budget_row_year_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="logisticsuploads",
            name="created_by",
            field=models.ForeignKey(
                max_length=5000,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="LogisticsUploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
