# Generated by Django 5.0.1 on 2024-10-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tadbirbodjeh", "0005_remove_relation_cost_type_remove_relation_programs"),
    ]

    operations = [
        migrations.AddField(
            model_name="relation",
            name="cost_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="relation",
            name="programs",
            field=models.ManyToManyField(
                related_name="relations", to="tadbirbodjeh.program"
            ),
        ),
    ]
