# Generated by Django 5.0.1 on 2024-11-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tadbirbodjeh", "0005_contract_contractor_level_contract_record_vat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract_record",
            name="descr",
        ),
        migrations.RemoveField(
            model_name="contract_record",
            name="paid_amount",
        ),
        migrations.AddField(
            model_name="contract_record",
            name="Contractor_level",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="Contractor_level",
            field=models.CharField(max_length=2, null=True),
        ),
    ]
