# Generated by Django 5.0.1 on 2024-11-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tadbirbodjeh", "0006_remove_contract_record_descr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor_type",
            name="Contractor_level",
            field=models.CharField(max_length=2, null=True),
        ),
    ]
