# Generated by Django 5.0.1 on 2024-10-01 10:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tadbirbodjeh", "0006_relation_cost_type_relation_programs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relation",
            name="budget_sub_row",
        ),
    ]
