# Generated by Django 5.0 on 2024-03-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tadbirbodjeh", "0006_remove_logistics_upload_ids_logistics_uploads"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logistics",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
