# Generated by Django 5.0.1 on 2024-11-10 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tadbirbodjeh", "0007_contractor_type_contractor_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="Contract_record",
        ),
        migrations.AddField(
            model_name="contract_record",
            name="Contract",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract_record",
                to="tadbirbodjeh.contract",
            ),
        ),
    ]
