# Generated by Django 5.0.1 on 2024-10-05 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tadbirbodjeh", "0007_remove_relation_budget_sub_row"),
    ]

    operations = [
        migrations.DeleteModel(
            name="credit",
        ),
        migrations.AddField(
            model_name="logistics",
            name="budget_row",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Logistics",
                to="tadbirbodjeh.budget_row",
            ),
        ),
        migrations.AddField(
            model_name="logistics",
            name="program",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Logistics",
                to="tadbirbodjeh.program",
            ),
        ),
    ]
