# Generated by Django 5.0 on 2024-03-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tadbirbodjeh", "0008_alter_logistics_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financial",
            name="CostType",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="financial",
            name="date_doc",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="financial",
            name="descr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="financial",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="financial",
            name="programId",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="financial",
            name="rowId",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="financial",
            name="topicId",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
