# Generated by Django 5.0.1 on 2024-11-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tadbirbodjeh", "0008_remove_contract_contract_record_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract_record",
            name="descr",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="uploads",
            field=models.ManyToManyField(
                blank=True, to="tadbirbodjeh.logisticsuploads"
            ),
        ),
    ]
