# Generated by Django 5.0 on 2024-04-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tadbirbodjeh",
            "0009_alter_financial_costtype_alter_financial_date_doc_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="financial",
            name="tax",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
