# Generated by Django 5.0.1 on 2024-07-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tadbirbodjeh", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="logistics",
            name="account_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="logistics",
            name="account_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="logistics",
            name="bank_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="logistics",
            name="vat",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
