# Generated by Django 5.0.1 on 2024-10-27 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tadbirbodjeh", "0002_remove_relation_budget_row_remove_relation_updated"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contractor_type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="relation",
            name="budget_row",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="relations",
                to="tadbirbodjeh.budget_row",
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="organization",
            field=models.ManyToManyField(
                related_name="relations", to="tadbirbodjeh.organization"
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="programs",
            field=models.ManyToManyField(
                related_name="relations", to="tadbirbodjeh.program"
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("Contractor", models.CharField(blank=True, max_length=255)),
                ("Contractor_id", models.CharField(blank=True, max_length=255)),
                ("contract_number", models.CharField(blank=True, max_length=255)),
                ("document_date", models.DateTimeField(blank=True)),
                ("total_contract_amount", models.FloatField(blank=True, null=True)),
                ("paid_amount", models.FloatField(blank=True, null=True)),
                (
                    "requested_performance_amount",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "treasury_deduction_percent",
                    models.CharField(blank=True, max_length=255),
                ),
                ("overhead_percentage", models.CharField(blank=True, max_length=255)),
                (
                    "payable_amount_after_deductions",
                    models.CharField(blank=True, max_length=255),
                ),
                ("tax_percentage", models.CharField(blank=True, max_length=255)),
                ("tax_amount", models.CharField(blank=True, max_length=255)),
                ("final_payable_amount", models.CharField(blank=True, max_length=255)),
                ("descr", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                ("cost_type", models.IntegerField(blank=True, null=True)),
                (
                    "Location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Contractor",
                        to="tadbirbodjeh.sub_unit",
                    ),
                ),
                (
                    "budget_row",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Contractor",
                        to="tadbirbodjeh.budget_row",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Contractor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Contractor",
                        to="tadbirbodjeh.program",
                    ),
                ),
                (
                    "uploads",
                    models.ManyToManyField(
                        blank=True, to="tadbirbodjeh.logisticsuploads"
                    ),
                ),
                (
                    "Contractor_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Contractor",
                        to="tadbirbodjeh.contractor_type",
                    ),
                ),
            ],
        ),
    ]
