# Generated by Django 5.0.1 on 2024-09-16 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tadbirbodjeh", "0007_alter_logisticsuploads_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget_chapter",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="logisticsuploads",
            name="file",
            field=models.FileField(max_length=1000, upload_to="./uploads/"),
        ),
        migrations.CreateModel(
            name="budget_sub_row",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(blank=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("year", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "budget_row",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_sub_row",
                        to="tadbirbodjeh.budget_section",
                    ),
                ),
            ],
        ),
    ]
