# Generated by Django 5.0.1 on 2024-09-16 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tadbirbodjeh",
            "0008_budget_chapter_updated_alter_logisticsuploads_file_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget_sub_row",
            name="budget_row",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budget_sub_row",
                to="tadbirbodjeh.budget_row",
            ),
        ),
    ]
