# Generated by Django 5.0.1 on 2024-09-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tadbirbodjeh", "0009_alter_budget_sub_row_budget_row"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget_chapter",
            name="fin_code",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="budget_row",
            name="fin_code",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="budget_section",
            name="fin_code",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="budget_sub_row",
            name="fin_code",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="code",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="year",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="code",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="year",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="budget_chapter",
            name="code",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="budget_row",
            name="code",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="budget_section",
            name="code",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="budget_sub_row",
            name="code",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
